// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UKHO.ADDS.Clients.Kiota.FileShareService.Batch.Item.Acl
{
    /// <summary>
    /// The ACL describes which users or groups will be able to read files in this batch once it has been committed.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AclPutRequestBody : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of group names that can read this batch. This property must be present and the list will replace the existing list of read groups.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ReadGroups { get; set; }
#nullable restore
#else
        public List<string> ReadGroups { get; set; }
#endif
        /// <summary>List of AD/B2C Object IDs for the individual users that can read this batch. This property must be present and the list will replace the existing list of read users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ReadUsers { get; set; }
#nullable restore
#else
        public List<string> ReadUsers { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.Item.Acl.AclPutRequestBody"/> and sets the default values.
        /// </summary>
        public AclPutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.Item.Acl.AclPutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.Item.Acl.AclPutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.Item.Acl.AclPutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "readGroups", n => { ReadGroups = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "readUsers", n => { ReadUsers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("readGroups", ReadGroups);
            writer.WriteCollectionOfPrimitiveValues<string>("readUsers", ReadUsers);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
