name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(BuildCounter)

trigger:
- main

pool: NautilusBuild

variables:
- name: BuildConfiguration
  value: "Release"
- name: BuildPlatform
  value: "any cpu"
- name: BuildCounter
  value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
- name: UKHOAssemblyCompany
  value: "UK Hydrographic Office"
- name: UKHOAssemblyVersionPrefix
  value: "0.0."
- name: UKHOAssemblyProduct
  value: "ADDS Shared Clients"
- name: SdkVersion
  value: "8.0.x"

resources:
  repositories:
  - repository: openApiSpecSalesCatalogueServiceSharedAssets
    type: github
    name: UKHO/Sales-Catalogue-Service-Shared-Assets
    ref: refs/heads/main
    endpoint: UKHO

  - repository: openApiSpecFileShareService
    type: github
    name: UKHO/file-share-service
    ref: refs/heads/main
    endpoint: UKHO

stages:
- stage: BuildTestPublish
  displayName: Build, test and publish
  dependsOn: []
  jobs:
  - job: MainBuild
    workspace:
      clean: all
    displayName: Build, unit test and package
    steps:
    - checkout: self
      path: s

    - task: PowerShell@2
      displayName: Output environment variables
      inputs:
        targetType: inline
        script: |
          gci env:
          $CurrentYear = Get-Date -Format "yyyy"
          $AssemblyCopyright = "Copyright © UK Hydrographic Office $CurrentYear"
          echo "##vso[task.setvariable variable=UKHOAssemblyCopyright]${AssemblyCopyright}"

    - task: PowerShell@2
      displayName: Set assembly version numbers based on build ID
      name: SetAssemblyVersion
      inputs:
        targetType: filePath
        filePath: '$(Build.SourcesDirectory)\deployment\Apply-AssemblyVersionAndDefaults.ps1'
        arguments: >
          -buildNumber "$(Build.BuildNumber)"
          -solutionDirectory "$(Build.SourcesDirectory)\"
          -UKHOAssemblyCompany "$env:UKHOAssemblyCompany"
          -UKHOAssemblyCopyright "$env:UKHOAssemblyCopyright"
          -UKHOAssemblyVersionPrefix "$env:UKHOAssemblyVersionPrefix"
          -UKHOAssemblyProduct "$env:UKHOAssemblyProduct"
          -SourceRevisionId "$(Build.SourceVersion)"

    - task: UseDotNet@2
      displayName: Use .NET $(SdkVersion) sdk
      inputs:
        packageType: sdk
        version: $(SdkVersion)

    - task: DotNetCoreCLI@2
      displayName: Package restore
      inputs:
        command: restore
        projects: |
          **/*.csproj
        feedsToUse: config
        noCache: true
        nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
        workingDirectory: '$(Build.SourcesDirectory)'
        packagesDirectory: '$(Build.SourcesDirectory)\packages'

    - task: DotNetCoreCLI@2
      displayName: Unit tests
      inputs:
        command: test
        projects: |
          **/*.Tests.csproj
        testRunTitle: UnitTests
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: DotNetCoreCLI@2
      displayName: Pack libraries
      inputs:
        command: pack
        packagesToPack: >
          **/UKHO.ADDS.Clients.Common.csproj;
          **/UKHO.ADDS.Clients.FileShareService.ReadOnly.csproj;
          **/UKHO.ADDS.Clients.FileShareService.ReadWrite.csproj;
          **/UKHO.ADDS.Clients.PermitService.csproj;
          **/UKHO.ADDS.Clients.SalesCatalogueService.csproj
        packDirectory: $(Build.ArtifactStagingDirectory)/packages
        arguments:  '--configuration $(BuildConfiguration)'
          
    - task: PublishPipelineArtifact@1
      displayName: Publish NuGet packages
      inputs:
        path: $(Build.ArtifactStagingDirectory)/packages
        artifact: NuGetPackages

    - template: /deployment/integration-test-build.yml
      parameters:
        ProjectPartialName: FileShareService.ReadOnly

    - template: /deployment/integration-test-build.yml
      parameters:
        ProjectPartialName: FileShareService.ReadWrite

    - template: /deployment/integration-test-build.yml
      parameters:
        ProjectPartialName: PermitService

    - template: /deployment/integration-test-build.yml
      parameters:
        ProjectPartialName: SalesCatalogueService

    - task: PublishPipelineArtifact@1
      displayName: Publish integration tests artifact
      inputs:
        path: $(Build.BinariesDirectory)\IntegrationTests
        artifact: IntegrationTests

  - job:
    dependsOn: MainBuild
    displayName: Integration tests
    # variables:
    # - group: clients-integration-tests
    steps:
    - checkout: none
  
    - download: current
      displayName: Download integration tests
      artifact: IntegrationTests

    # - task: FileTransform@2
    #   displayName: File transform - FileShareService.ReadOnly
    #   inputs:
    #     folderPath: $(Pipeline.Workspace)\IntegrationTests\FileShareService.ReadOnly
    #     xmlTransformationRules:
    #     jsonTargetFiles: 'appsettings.json'

    # - task: FileTransform@2
    #   displayName: File transform - FileShareService.ReadWrite
    #   inputs:
    #     folderPath: $(Pipeline.Workspace)\IntegrationTests\FileShareService.ReadWrite
    #     xmlTransformationRules:
    #     jsonTargetFiles: 'appsettings.json'

    # - task: FileTransform@2
    #   displayName: File transform - PermitService
    #   inputs:
    #     folderPath: $(Pipeline.Workspace)\IntegrationTests\PermitService
    #     xmlTransformationRules:
    #     jsonTargetFiles: 'appsettings.json'

    # - task: FileTransform@2
    #   displayName: File transform - SalesCatalogueService
    #   inputs:
    #     folderPath: $(Pipeline.Workspace)\IntegrationTests\SalesCatalogueService
    #     xmlTransformationRules:
    #     jsonTargetFiles: 'appsettings.json'

    # - task: DotNetCoreCLI@2
    #   displayName: Run integration tests
    #   inputs:
    #     command: test
    #     projects: |
    #       $(Pipeline.Workspace)\IntegrationTests\FileShareService.ReadOnly\UKHO.ADDS.Clients.FileShareService.ReadOnly.IntegrationTests.dll
    #       $(Pipeline.Workspace)\IntegrationTests\FileShareService.ReadWrite\UKHO.ADDS.Clients.FileShareService.ReadWrite.IntegrationTests.dll
    #       $(Pipeline.Workspace)\IntegrationTests\PermitService\UKHO.ADDS.Clients.PermitService.IntegrationTests.dll
    #       $(Pipeline.Workspace)\IntegrationTests\SalesCatalogueService\UKHO.ADDS.Clients.SalesCatalogueService.IntegrationTests.dll
    #     testRunTitle: IntegrationTests

    - template: deployment/KiotaGenerateClients.yml
      parameters:
        openApiRepo: 'openApiSpecSalesCatalogueServiceSharedAssets'
        openApiSpecPath: 'salesCatalogue_ExchangeSetService_API_definition_v1.10.yaml'
        outputDirectory: '$(Build.SourcesDirectory)\src\UKHO.ADDS.Clients.KiotaSalesCatalogueService\GeneratedClient'
        language: 'csharp'
        GeneratedApiClassName: 'KiotaSalesCatalogueService'
        Namespace: 'UKHO.ADDS.Clients.Kiota.SalesCatalogueService'

    - template: deployment/KiotaGenerateClients.yml
      parameters:
        openApiRepo: 'openApiSpecFileShareService'
        openApiSpecPath: 'file-share-service.openApi-public.yaml'
        outputDirectory: '$(Build.SourcesDirectory)\src\UKHO.ADDS.Clients.FileShareService.ReadOnly\GeneratedClient'
        language: 'csharp'
        GeneratedApiClassName: 'KiotaFileShareService'
        Namespace: 'UKHO.ADDS.Clients.Kiota.FileShareService.ReadOnly'

    - template: deployment/KiotaGenerateClients.yml
      parameters:
        openApiRepo: 'openApiSpecFileShareService'
        openApiSpecPath: 'file-share-service.openApi.yaml'
        outputDirectory: '$(Build.SourcesDirectory)\src\UKHO.ADDS.Clients.FileShareService.ReadWrite\GeneratedClient'
        language: 'csharp'
        GeneratedApiClassName: 'KiotaFileShareService'
        Namespace: 'UKHO.ADDS.Clients.Kiota.FileShareService.ReadWrite'

- stage: ProGet
  # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
  - group: nuget-deployment-vars
  jobs:
  - deployment: Publish_To_ProGetCloud
    displayName: Publish To ProGetCloud
    pool:
      name: NautilusRelease
    environment: UKHO-ADDS-Clients-ProGet
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UseDotNet@2
            displayName: 'Use .NET $(SdkVersion) sdk'
            inputs:
              packageType: sdk
              version: $(SdkVersion)

          - download: current
            artifact: NuGetPackages

          - powershell: Get-ChildItem "$(Pipeline.Workspace)/NuGetPackages/*.nupkg" -File | Foreach {dotnet nuget push $_.fullname -k $(progetApiKey) -s https://progetcloud.ukho.gov.uk/nuget/ukho.trusted/v3/index.json }
            env:
              progetApiKey : $(progetApiKey)
            displayName: Publish Package

- stage: NuGet
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
  - group: nuget-deployment-vars
  jobs:
  - deployment: Publish_To_NuGet
    displayName: Publish To NuGet
    pool:
      name: NautilusRelease
    environment: UKHO-ADDS-Clients-NuGet
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UseDotNet@2
            displayName: 'Use .NET $(SdkVersion) sdk'
            inputs:
              packageType: sdk
              version: $(SdkVersion)

          - download: current
            artifact: NuGetPackages

          - powershell: Get-ChildItem "$(Pipeline.Workspace)/NuGetPackages/*.nupkg" -File | Foreach {dotnet nuget push $_.fullname -k $(nugetapikey) -s https://api.nuget.org/v3/index.json --no-symbols}
            env:
              nugetApiKey : $(nugetapikey)
            displayName: Publish Package
