// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UKHO.ADDS.Clients.Kiota.FileShareService.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BatchDetails_files : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files_attributes>? Attributes { get; set; }
#nullable restore
#else
        public List<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files_attributes> Attributes { get; set; }
#endif
        /// <summary>The filename property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Filename { get; set; }
#nullable restore
#else
        public string Filename { get; set; }
#endif
        /// <summary>The fileSize property</summary>
        public int? FileSize { get; set; }
        /// <summary>MD5 hash of the file content.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hash { get; set; }
#nullable restore
#else
        public string Hash { get; set; }
#endif
        /// <summary>Contains links to the relevant APIs for this file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files_links? Links { get; set; }
#nullable restore
#else
        public global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files_links Links { get; set; }
#endif
        /// <summary>The MIME content type of the file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MimeType { get; set; }
#nullable restore
#else
        public string MimeType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files"/> and sets the default values.
        /// </summary>
        public BatchDetails_files()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetCollectionOfObjectValues<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files_attributes>(global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files_attributes.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fileSize", n => { FileSize = n.GetIntValue(); } },
                { "filename", n => { Filename = n.GetStringValue(); } },
                { "hash", n => { Hash = n.GetStringValue(); } },
                { "links", n => { Links = n.GetObjectValue<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files_links>(global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files_links.CreateFromDiscriminatorValue); } },
                { "mimeType", n => { MimeType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files_attributes>("attributes", Attributes);
            writer.WriteStringValue("filename", Filename);
            writer.WriteIntValue("fileSize", FileSize);
            writer.WriteStringValue("hash", Hash);
            writer.WriteObjectValue<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails_files_links>("links", Links);
            writer.WriteStringValue("mimeType", MimeType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
