// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UKHO.ADDS.Clients.Kiota.FileShareService.Attributes;
using UKHO.ADDS.Clients.Kiota.FileShareService.Auth;
using UKHO.ADDS.Clients.Kiota.FileShareService.Batch;
using UKHO.ADDS.Clients.Kiota.FileShareService.Heartbeat;
namespace UKHO.ADDS.Clients.Kiota.FileShareService
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KiotaFileShareService : BaseRequestBuilder
    {
        /// <summary>The attributes property</summary>
        public global::UKHO.ADDS.Clients.Kiota.FileShareService.Attributes.AttributesRequestBuilder Attributes
        {
            get => new global::UKHO.ADDS.Clients.Kiota.FileShareService.Attributes.AttributesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::UKHO.ADDS.Clients.Kiota.FileShareService.Auth.AuthRequestBuilder Auth
        {
            get => new global::UKHO.ADDS.Clients.Kiota.FileShareService.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The batch property</summary>
        public global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchRequestBuilder Batch
        {
            get => new global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The heartbeat property</summary>
        public global::UKHO.ADDS.Clients.Kiota.FileShareService.Heartbeat.HeartbeatRequestBuilder Heartbeat
        {
            get => new global::UKHO.ADDS.Clients.Kiota.FileShareService.Heartbeat.HeartbeatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.FileShareService.KiotaFileShareService"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KiotaFileShareService(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "http://fss.ukho.gov.uk";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
