// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Batch.Item.Status
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StatusGetResponse_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Incomplete")]
        #pragma warning disable CS1591
        Incomplete,
        #pragma warning restore CS1591
        [EnumMember(Value = "CommitInProgress")]
        #pragma warning disable CS1591
        CommitInProgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "Committed")]
        #pragma warning disable CS1591
        Committed,
        #pragma warning restore CS1591
        [EnumMember(Value = "Rolledback")]
        #pragma warning disable CS1591
        Rolledback,
        #pragma warning restore CS1591
        [EnumMember(Value = "Failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
    }
}
