// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
using UKHO.ADDS.Clients.Kiota.FileShareService.Models;
namespace UKHO.ADDS.Clients.Kiota.FileShareService.Batch
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BatchGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of batches that are in this page of the result. If there is only one page of results, this will equal `total`.</summary>
        public int? Count { get; set; }
        /// <summary>The entries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails>? Entries { get; set; }
#nullable restore
#else
        public List<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails> Entries { get; set; }
#endif
        /// <summary>Links, usually describing links to next and previous pages in a paged result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UKHO.ADDS.Clients.Kiota.FileShareService.Models._links? Links { get; set; }
#nullable restore
#else
        public global::UKHO.ADDS.Clients.Kiota.FileShareService.Models._links Links { get; set; }
#endif
        /// <summary>Total number of batches that match the query.</summary>
        public int? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchGetResponse"/> and sets the default values.
        /// </summary>
        public BatchGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "count", n => { Count = n.GetIntValue(); } },
                { "entries", n => { Entries = n.GetCollectionOfObjectValues<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails>(global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails.CreateFromDiscriminatorValue)?.AsList(); } },
                { "_links", n => { Links = n.GetObjectValue<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models._links>(global::UKHO.ADDS.Clients.Kiota.FileShareService.Models._links.CreateFromDiscriminatorValue); } },
                { "total", n => { Total = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("count", Count);
            writer.WriteCollectionOfObjectValues<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models.BatchDetails>("entries", Entries);
            writer.WriteObjectValue<global::UKHO.ADDS.Clients.Kiota.FileShareService.Models._links>("_links", Links);
            writer.WriteIntValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
