// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UKHO.ADDS.Clients.Kiota.FileShareService.Batch
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BatchPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ACL describes which users or groups will be able to read files in this batch once it has been committed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody_acl? Acl { get; set; }
#nullable restore
#else
        public global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody_acl Acl { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody_attributes>? Attributes { get; set; }
#nullable restore
#else
        public List<global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody_attributes> Attributes { get; set; }
#endif
        /// <summary>The business unit that this data is being hosted for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessUnit { get; set; }
#nullable restore
#else
        public string BusinessUnit { get; set; }
#endif
        /// <summary>Optional expiry date for the batch.</summary>
        public DateTimeOffset? ExpiryDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody"/> and sets the default values.
        /// </summary>
        public BatchPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acl", n => { Acl = n.GetObjectValue<global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody_acl>(global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody_acl.CreateFromDiscriminatorValue); } },
                { "attributes", n => { Attributes = n.GetCollectionOfObjectValues<global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody_attributes>(global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody_attributes.CreateFromDiscriminatorValue)?.AsList(); } },
                { "businessUnit", n => { BusinessUnit = n.GetStringValue(); } },
                { "expiryDate", n => { ExpiryDate = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody_acl>("acl", Acl);
            writer.WriteCollectionOfObjectValues<global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.BatchPostRequestBody_attributes>("attributes", Attributes);
            writer.WriteStringValue("businessUnit", BusinessUnit);
            writer.WriteDateTimeOffsetValue("expiryDate", ExpiryDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
