// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UKHO.ADDS.Clients.Kiota.FileShareService.Batch.Item.Acl
{
    /// <summary>
    /// The ACL describes which users or groups will be able to read files in this batch once it has been committed.
    /// </summary>
    [Obsolete("This class is obsolete. Use AclGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AclResponse : global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.Item.Acl.AclGetResponse, IParsable
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.Item.Acl.AclResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.Item.Acl.AclResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::UKHO.ADDS.Clients.Kiota.FileShareService.Batch.Item.Acl.AclResponse();
        }
    }
}
#pragma warning restore CS0618
